# Generated by Django 5.2.1 on 2025-06-06 02:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('received_from', models.CharField(max_length=100)),
                ('house_name', models.CharField(max_length=100)),
                ('forwarded_to', models.CharField(max_length=100)),
                ('complaint_1', models.TextField(blank=True, null=True)),
                ('complaint_2', models.TextField(blank=True, null=True)),
                ('complaint_3', models.TextField(blank=True, null=True)),
                ('complaint_4', models.TextField(blank=True, null=True)),
                ('complaint_5', models.TextField(blank=True, null=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('date_solved', models.DateField(blank=True, null=True)),
                ('solved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('solution_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
